package com.example.sudoku;

import android.content.Context;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.IOException;
import java.io.InputStream;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Random;

public class WordList {
    // name of JSON file to retrieve words
    private static final String fileName = "wordsSmall.json";

    // number of words in file
    private static final int fileWordCount = 46;

    // list of english french words generated by constructor
    public List<String> englishWordList = new ArrayList<>();
    public List<String> frenchWordList = new ArrayList<>();

    // number of words required by sudoku grid: length of englishWordList and frenchWordList
    private final int wordCount;

    /**
     * Get English word at index
     *
     * @param index of word in List
     * @return english word at index
     */
    public String getEnglishWord(int index) {
        return englishWordList.get(index);
    }

    /**
     * Get French word at index
     *
     * @param index of word in List
     * @return french word at index
     */
    public String getFrenchWord(int index) {
        return frenchWordList.get(index);
    }

    /**
     *
     * @return length of lists
     */
    public int length() {
        return wordCount;
    }

    /**
     * Constructor for WordList:
     * Call getEnglishWord(index) to get english word at index,
     * call getFrenchWord(index) to get french word at index
     *
     * @param wordCount number of words required by sudoku grid
     */
    public WordList(int wordCount) {
        this.wordCount = wordCount;
    }

    public void randomWords(Context context) {
        try {
            // retrieve JSON data from file
            JSONObject obj = new JSONObject(Objects.requireNonNull(loadJSONFromAssets(context)));
            JSONArray array = obj.getJSONArray("words");

            Random rand = new Random();

            // add randomly chosen words to englishWordList and frenchWordList
            int i = 0;
            while (i < wordCount) {
                // get random index
                int index = rand.nextInt(fileWordCount);

                // random word from file
                JSONObject wordAtIndex = array.getJSONObject(index);

                String englishWord = wordAtIndex.getString("english");
                String frenchWord = wordAtIndex.getString("french");

                // if wordAtIndex is not a duplicate, add englishWord and frenchWord to corresponding list
                if (!englishWordList.contains(englishWord) && !frenchWordList.contains(frenchWord)) {
                    englishWordList.add(englishWord);
                    frenchWordList.add(frenchWord);
                    i++;
                }
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }
    /**
     * Method to load JSON file from assets folder
     *
     * @param context context of activity
     * @return JSON data
     */
    public static String loadJSONFromAssets(Context context) {
        try {
            InputStream is = context.getAssets().open(fileName);
            int size = is.available();
            byte[] buffer = new byte[size];
            is.read(buffer);
            is.close();
            return new String(buffer, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            ex.printStackTrace();
            return null;
        }
    }
}
